language: go
go:
 - 1.8.1
before_script:
 - git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
 - go get -u -v github.com/spf13/hugo
script:
 - git submodule init
 - hugo
