version: "3.6"
services:
  builder:
    build: .
    command: hugo
    volumes:
    - ./:/opt/gamingonhaiku.cf
  publisher:
    build: .
    command: netlify deploy --dir=public --prod
    environment: 
      NETLIFY_AUTH_TOKEN:
      NETLIFY_SITE_ID: 9c1fff50-2021-4ccd-ba58-efd689e8f499
    volumes:
    - ./:/opt/gamingonhaiku.cf